build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Charly Micolas - Developer"
    email: "charly@gmail.com"
  onCallSupport:
    - (+62) 812-1872-8890

