build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Niko - QA Lead"
    email: "niko@gmail.com"
  onCallSupport:
    - (+62) 812-1872-8881