build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contactDetails:
    name: "Charly Micolas - Developer"
    email: "charly@gmail.com"
  onCallSupport:
    - (+62) 812-1872-8880

