build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Niko - QA Lead"
    email: "niko@gmail.com"
  onCallSupport:
    - (+62) 812-1872-8871