spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Eben Ezer - Product Owner"
    email: "ebenezer@gmail.com"
  onCallSupport:
    - (+62) 812-1872-8892